Allow nested attributes as array
yiisoft/form pull request #186
Opened 2022-03-12 19:14 UTC by Gerych1984

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

Allow both syntax for nesteds `FormModel`. Previous `attribute.nested = value` and as simple array (for example from $_GET/$_POST)
```
[
    'attribute' => [
        'nested' => 'value',
    ],
]
```

2022-03-12 19:34 UTC, xepozz requested changes
Looks good. Do we still need to support notation with `.`?

2022-03-12 19:34 UTC, xepozz commented on src/FormModel.php
> +        };
```suggestion
            $attribute = $class->$attribute;
            if (!is_object($attribute) || !$attribute instanceof self::class) {
                $class->$attribute = $value;
                return;
            }
            if ($nested !== null) {
                $attribute->setAttribute($nested, $value);
                return;
            }
            if (is_array($value)) {
                $attribute->load($value, '');
                return;
            }
            
            throw new RuntimeException('$value must be array for using as nested attribute');
        };
```

2022-03-12 19:34 UTC, xepozz commented on tests/FormModelTest.php
> +        $this->assertSame('admin', $form->getUserLogin());
```suggestion
        $this->assertEquals('admin', $form->getUserLogin());
```

2022-03-13 08:03 UTC, Gerych1984 commented
> Looks good. Do we still need to support notation with `.`?

Good day. I use this trick in my project just two days (for generate standart querystrings in js components). I think it can be saved for BC for first time, but also need changes in `HtmlForm` helper for generate input names wo dots. Anyway - now i have two cases, on plain html using `.` from helper, and generated from js as standart arrays

2022-03-13 09:11 UTC, xepozz commented
But original HTML Forms send nested attributes with `[]`. So user can use brackets notation instead of dot.

2022-03-13 09:25 UTC, Gerych1984 commented
> But original HTML Forms send nested attributes with `[]`. So user can use brackets notation instead of dot.

Of course and works with standart arrays more convenient in my opinion. But in current time my most difficult form has max 4th nested levels and input name generated something like `Search[addreesses.k_numbers.fiases.ids]` etc. It only way to generate it using `HtmlForm` helper and it's not was big problem before i need generate same querystring using js/vue.

2022-03-13 10:22 UTC, xepozz commented
But what's the difference between `Search[addreesses.k_numbers.fiases.ids]` and `Search[addreesses[k_numbers[fiases[ids]]]]` if it is generated with a class-helper and is parsed by form?

2022-03-13 10:39 UTC, Gerych1984 commented
> But what's the difference between `Search[addreesses.k_numbers.fiases.ids]` and `Search[addreesses[k_numbers[fiases[ids]]]]` if it is generated with a class-helper and is parsed by form?

Roight format that can be using native php without any parsers must be `Search[addresses][k_numbers][fiases][ids]`. That PR can be first step to do it

2022-03-13 14:10 UTC, terabytesoftw commented
Forms must support the `Nested::class` Validator syntax, support .dot format.

2023-12-04 14:07 UTC, closed without merging