Clean up `php 8.0`.
yiisoft/form pull request #190
Opened 2022-03-30 23:17 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌

- [x] Add union types.
- [x] Fix phpdoc.
- [x] Add use function. 
- [x] Upload code coverage 100%.
- [x] Upload infection 99%.
- [x] Clean up code.
- [x] Add more tests.

2022-03-31 21:05 UTC, samdark requested changes

2022-03-31 21:05 UTC, samdark commented on src/Widget/Form.php
> +     * The action and formation content attributes, if specified, must have a value that is a valid non-empty URL
No, it was correct.

2022-03-31 21:26 UTC, terabytesoftw commented on src/FormModel.php
> +    public function getAttributeCastValue(string $attribute): iterable|int|float|string|bool|object|null
done.

2022-03-31 21:40 UTC, terabytesoftw commented on src/Widget/Attribute/FieldAttributes.php
> +        $new->defaultTokens[$token] = $value instanceof Stringable ? $value->__toString() : $value;
done.

2022-03-31 21:41 UTC, terabytesoftw commented on src/Widget/Field.php
> +     *     'groups()' => [['1' => ['2' => 'Moscow', '3' => 'San Petersburg']]],
done.

2022-03-31 21:43 UTC, terabytesoftw commented on src/Widget/Form.php
> +     * The action and formation content attributes, if specified, must have a value that is a valid non-empty URL
done.

2022-04-01 15:07 UTC, samdark approved these changes

2022-04-01 15:07 UTC, merged

2022-04-01 15:07 UTC, samdark commented
👍