Implement `FormCollector::class`.
yiisoft/form pull request #229
Opened 2022-08-23 12:59 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2022-10-05 10:32 UTC, xepozz requested changes
👍

2022-10-05 10:32 UTC, xepozz commented on tests/FormCollectorTest.php
> +    public function testSetValue(): void
Please use `@dataProvider` instead

2022-10-05 10:32 UTC, xepozz commented on src/FormCollector.php
> +        [$this->attributes, $this->rules] = $this->collectorAttributes();
Isn't it better to do it in each any public methods to prevent collecting rules and attributes at the creation time? Kind of lazy initialization.

2022-10-05 10:32 UTC, xepozz commented on src/FormModel.php
> +    public function getFormCollector(): FormCollector
Is it really needed?

2022-10-05 10:32 UTC, xepozz commented on src/FormCollector.php
> +final class FormCollector
I would mark it as `@internal`

2022-12-10 16:28 UTC, vjik requested changes
Suggest use `ObjectParser` from validator for get rules from form.

2023-09-25 14:03 UTC, closed without merging