Docs additions, field common methods
yiisoft/form pull request #334
Opened 2024-06-06 13:28 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-06-11 15:28 UTC, samdark approved these changes

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/base-field/container.md
> +When no specified, `div` tag is used.
```suggestion
When not specified, `div` tag is used.
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/base-field/container.md
> +Note that values within the same attribute will not be merged, newly added overrides previous ones:
```suggestion
Note that values within the same attribute will not be merged, newly added value overrides previous ones:
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/base-field/container.md
> +To add classes to the existing ones:
```suggestion
To add classes to existing ones:
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/input-field/field.md
> +Input field is a parts field with exactly 1 input element.
What is "parts field"?

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/input-field/field.md
> +To add attributes to the existing ones:
```suggestion
To add attributes to existing ones:
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/input-field/field.md
> +Note that values within the same attribute will not be merged, newly added overrides previous ones:
```suggestion
Note that values within the same attribute will not be merged, newly added value overrides previous ones:
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/field.md
> +Note that values within the same attribute will not be merged, newly added overrides previous ones:
```suggestion
Note that values within the same attribute will not be merged, newly added value overrides previous ones:
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +When no specified, no container is used for input.
```suggestion
When not specified, no container is used for input.
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +HTML attributes for outer container that wraps the input. Input container tag must be specified too in order for
```suggestion
HTML attributes for outer container that wraps the input. Input container tag must be specified for
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +When no specified, no attributes are used for input.
```suggestion
When not specified, no attributes are used for input.
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +Note that values within the same attribute will not be merged, newly added overrides previous ones:
```suggestion
Note that values within the same attribute will not be merged, newly added value overrides previous ones:
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +HTML class for outer container that wraps the input. Input container tag must be specified too in order for container to
```suggestion
HTML class for outer container that wraps the input. Input container tag must be specified for container to
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +When no specified, no class is used for input.
```suggestion
When not specified, no class is used for input.
```

2024-06-11 15:28 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/input-container.md
> +To add classes to the existing ones:
```suggestion
To add classes to existing ones:
```

2024-06-12 11:35 UTC, arogachev commented on docs/guide/en/field-common-methods/input-field/field.md
> +Input field is a parts field with exactly 1 input element.
Maybe add link to parts field here?

2024-06-13 09:41 UTC, vjik requested changes
My suggestion: https://github.com/yiisoft/form/pull/337

2024-06-13 17:12 UTC, samdark commented on docs/guide/en/field-common-methods/input-field/field.md
> +Input field is a parts field with exactly 1 input element.
Yes :+1:

2024-06-13 17:12 UTC, samdark commented on docs/guide/en/field-common-methods/parts-field/field.md
> +Input here can be composite and can contain multiple elements.
```suggestion
Input here can be composite and can contain multiple elements (parts).
```

2024-06-25 14:35 UTC, vjik requested changes

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +- Error.
```suggestion
- label;
- hint;
- input;
- error.
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Another way is to use [config].
Is missed link?

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Another way is to use [config].
Is missed link?

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Another way is to use [config].
Is missed link?

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Config with [definitions](https://github.com/yiisoft/definitions) for label.
```suggestion
Config with [definitions](https://github.com/yiisoft/definitions) for `Label` widget.
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Config with [definitions](https://github.com/yiisoft/definitions) for hint.
```suggestion
Config with [definitions](https://github.com/yiisoft/definitions) for `Hint` widget.
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Config with [definitions](https://github.com/yiisoft/definitions) for error.
```suggestion
Config with [definitions](https://github.com/yiisoft/definitions) for `Error` widget.
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The label must be visible (use [`label()`](#label) or [`labelConfig()](#labelconfig) methods).
```suggestion
> The label must be visible (use [`label()`](#label) or [`labelConfig()`](#labelconfig) methods).
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The hint must be visible (use [`hint()`](#hint) or [`hintConfig()](#hintconfig) methods).
```suggestion
> The hint must be visible (use [`hint()`](#hint) or [`hintConfig()`](#hintconfig) methods).
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The label must be visible (use [`label()`](#label) or [`labelConfig()](#labelconfig) methods).
```suggestion
> The label must be visible (use [`label()`](#label) or [`labelConfig()`](#labelconfig) methods).
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The hint must be visible (use [`hint()`](#hint) or [hintlConfig()](#hintconfig) methods).
```suggestion
> The hint must be visible (use [`hint()`](#hint) or [`hintConfig()`](#hintconfig) methods).
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The error must be visible (use [`error()`](#error) or [errorlConfig()](#errorconfig) methods).
```suggestion
> The error must be visible (use [`error()`](#error) or [`errorConfig()`](#errorconfig) methods).
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +```labelClass```
```suggestion
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The label must be visible (use [`label()`](#label) or [`labelConfig()](#labelconfig) methods).:
```suggestion
> The label must be visible (use [`label()`](#label) or [`labelConfig()`](#labelconfig) methods).:
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The hint must be visible (use [`hint()`](#hint) or [`hintConfig()](#hintconfig) methods).:
```suggestion
> The hint must be visible (use [`hint()`](#hint) or [`hintConfig()`](#hintconfig) methods).:
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +> The error must be visible (use [`error()`](#error) or [`errorConfig()](#errorconfig) methods).:
```suggestion
> The error must be visible (use [`error()`](#error) or [`errorConfig()`](#errorconfig) methods).:
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +`widget()` method.
```suggestion
A template for a field where tokens (placeholders) are field parts. This template is used when field is rendered.
```

2024-06-25 14:35 UTC, vjik commented on docs/guide/en/field-methods.md
> +Supported tokens:
```suggestion
Built-in tokens:
```

2024-06-27 09:26 UTC, vjik approved these changes

2024-06-27 09:30 UTC, merged