Move out setting of validation rules enricher from theme container
yiisoft/form pull request #351
Opened 2024-07-11 13:39 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-07-11 13:58 UTC, arogachev commented on src/Field/Base/DateTimeInputField.php
> +                ?? [];
Need to improve coverage.

2024-07-11 14:44 UTC, arogachev commented on docs/guide/en/validation-rules-enrichment.md
> +                ?->process($this, $this->getInputData()->getValidationRules())
Need to fix mutants.

2024-07-11 15:02 UTC, arogachev commented on docs/guide/en/validation-rules-enrichment.md
> +                ?->process($this, $this->getInputData()->getValidationRules())
#352

2024-07-12 18:24 UTC, vjik requested changes
Need way to globally set enricher.

2024-07-14 09:33 UTC, arogachev commented
@vjik Added support to set enricher globally via theme.

2024-07-14 09:37 UTC, vjik approved these changes
Remove `validationRulesEnricher` from `ThemeContainer` docs.

2024-07-14 12:00 UTC, vjik approved these changes

2024-07-14 14:24 UTC, samdark approved these changes

2024-07-15 12:24 UTC, merged